#!/usr/bin/env bash
# Writes the generated translation unit carrying the build time and git rev.
#
# Shared by build_lucid_dock.sh and CMakeLists.txt so the stamp has one format
# and one definition of "dirty", rather than two that drift.
#
# Why a .cpp and not a -D define or a generated header: the stamp has to be
# recomputed on every build to be true, and anything the main sources #include
# would then rebuild them every time. lucid_dock.cpp takes 5.7 s to compile and
# this file takes 0.01 s, so the changing value lives here, behind a header
# (build_stamp.h) whose contents never change.
set -euo pipefail

out="$1"
srcdir="${2:-.}"

stamp="$(date '+%Y-%m-%d %H:%M:%S')"
rev="$(git -C "$srcdir" rev-parse --short HEAD 2>/dev/null || echo unknown)"
dirty=""
git -C "$srcdir" diff --quiet 2>/dev/null || dirty="+dirty"

mkdir -p "$(dirname "$out")"
cat > "$out" <<EOF
// Generated by write_build_stamp.sh on every build. Do not edit, do not commit.
#include "build_stamp.h"

namespace lucid {
const char* const kBuildStamp = "$stamp";
const char* const kGitRev = "$rev$dirty";
}  // namespace lucid
EOF
